### ISSUE TITLE
Rk-More-Interactions not recognized by 3.19

### ISSUE THREAD

**Issue by Fortilicious** [RaiderKnight/RK-More-Interactions#1]
Mod is properly installed in the modules folder as C:\Users\Owner\Downloads\LifePlay_3_19_32bit\LifePlay\Content\Modules\rk_MoreInteractions

LifePlay is not even showing the mod in the mod manager.  Installing the Nick_No_mods compatibility fix did not fix the issue.

**Comment by Fortilicious** [comment]
3.20 is also not showing the mod on the list

**Comment by RaiderKnight** [comment]
Strange because on my side it works perfectly! Tomorrow I will check more in depth!

**Comment by RaiderKnight** [comment]
Seriously, I really don't know ! The mod contains only 4 files (1 lpaction, 2 lpscene and 1 lpmod). Have you tried downloading the mod a second time, sometimes files might get corrupted while unzipping or for mysterious reasons.

**Comment by RaiderKnight** [comment]
The problem is now solved!
It was a parsing issue caused by a gitattributes file.
I noticed this file, but didn't get any attention until the last few days.
All other mods that worked are the ones I downloaded through the Github website. And the ones that didn't work was the one I downloaded through Github Desktop .... which automatically generates a gitattributes file.
